dgg_auth_token = "authtoken here"
ogg_auth_token = "authtoken here"
sgg_auth_token = "authtoken here"
username = "cantclosevim"
timeformat = "3:04PM"
maxlines = 1000
scrolling_speed = 5
page_up_down_speed = 20
highlighted = ["cantclosevim", "vim"]
stalks = []
hide_nsfw = false
hide_nsfl = false
notifications = false
showjoinleave = false
highlight_bg_color = "\u001b[47m"
highlight_fg_color = "\u001b[30m"
load_history = true

[tags]
  cantclosevim = "cyan"
