auth_token = "authtoken here"
custom_url = "wss://chat.destiny.gg/ws"
username = "cantclosevim"
timeformat = "3:04PM"
maxlines = 1000
scrolling_speed = 5
page_up_down_Speed = 20
highlighted = ["cantclosevim", "vim"]
showjoinleave = false
legacyflairs = false
highlight_bg_color = "\u001b[47m"
highlight_fg_color = "\u001b[30m"
load_history = true
history_url = "https://www.destiny.gg/api/chat/history"
[tags]
  cantclosevim = "cyan"